version: '3.8'

services:
  web: 
    build: .
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_USER=flaskuser
      - POSTGRES_PASSWORD=flaskpass
      - POSTGRES_DB=flask_db
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data  # This references the volume
    environment:
      - POSTGRES_USER=flaskuser
      - POSTGRES_PASSWORD=flaskpass
      - POSTGRES_DB=flask_db
    ports:
      - "5432:5432"
    restart: unless-stopped

# THIS SECTION WAS MISSING - MUST DECLARE ALL NAMED VOLUMES
volumes:
  postgres_data:  # This declares the volume